### PR TITLE
Fix some test failures on Windows

### PR DESCRIPTION
**Pull request by bitfield**

### CODE REVIEW

**Comment by bitfield** [comment]
@No-one-important could you check if the tests now pass for you on your Windows environment?

**Comment by No-one-important** [comment]
```
--- FAIL: ExamplePipe_SHA256Sums (0.00s)
got:
4aea3d470d3f667fdd2dcdb9dbbc77db43872cfbfac1ce15682c4928eae9a146
want:
a562c9c95e2ff3403e7ffcd8508c6b54d47d5f251387758d3e63dbaaa8296341
FAIL
exit status 1
FAIL    github.com/bitfield/script      2.392s
```
still get the same fail

**Comment by bitfield** [comment]
@No-one-important that's the same diff as you saw originally, isn't it? Could you check what Git version you're using? This seems to be due to Git's auto-translation of line endings for what it considers "text" files. I've added a `.gitattributes` file which effectively marks all files as 'binary' (don't mess with line endings). 

It seems that not all versions of Git honour this—the test passes for some Windows users, but not others. It's known to work on Git `2.34.1.windows.1`.

**Comment by No-one-important** [comment]
git version 2.35.1.windows.1

**Comment by bitfield** [comment]
That's weird. Could you try deleting your copy of the repo and re-cloning?

**Comment by No-one-important** [comment]
I did already

**Comment by bitfield** [comment]
Well, if `ExamplePipe_SHA256Sums` is the only failure, I'll move that into `script_unix_test.go` so it won't be run on Windows. It will still be part of the autogenerated docs, which is the main thing. Otherwise, I think we're done!

**Comment by No-one-important** [comment]
its not the only failure i will atatch the rest later

**Comment by No-one-important** [comment]
[testOutput.zip](https://github.com/bitfield/script/files/8190439/testOutput.zip)

**Comment by bitfield** [comment]
Could you pull the latest changes? Your test output shows `filters_test.go`, for example—this no longer exists. Can you check that you've got commit ae524fda67d40dd63c8c1d50dd69f6def2b89194, and run the tests again, and paste the output of `go test` here? (Not `go test -json`—the string escaping makes it really hard to read the failures.)

**Comment by No-one-important** [comment]
```git show``` outputs
```
commit 91c46aa3bc7052e6209909775ed6e8003b6f88ec (HEAD -> master, tag: v0.18.4, origin/master, origin/HEAD)
Author: John Arundel <john@bitfieldconsulting.com>
Date:   Mon Feb 21 15:17:55 2022 +0000
````
```go test``` outputs
```
--- FAIL: TestBasename (0.00s)
    filters_test.go:36: "/": want "/\n", got "\\\n"
--- FAIL: TestLast (0.00s)
    filters_test.go:343: want "\r\nFree from desire, you realize the mystery.\r\nCaught in desire, you see only the manifestations.\r\n\r\nYet mystery and manifestations\r\narise from the same source.\r\nThis source is called darkness.\r\n\r\nDarkness within darkness.\r\nThe gateway to all understanding.\r\n", got "\nFree from desire, you realize the mystery.\nCaught in desire, you see only the manifestations.\n\nYet mystery and manifestations\narise from the same source.\nThis source is called darkness.\n\nDarkness within darkness.\nThe gateway to all understanding.\n"
    filters_test.go:382: want "The tao that can be told\r\nis not the eternal Tao\r\nThe name that can be named\r\nis not the eternal Name.\r\n\r\nThe unnamable is the eternally real.\r\nNaming is the origin\r\nof all particular things.\r\n\r\nFree from desire, you realize the mystery.\r\nCaught in desire, you see only the manifestations.\r\n\r\nYet mystery and manifestations\r\narise from the same source.\r\nThis source is called darkness.\r\n\r\nDarkness within darkness.\r\nThe gateway to all understanding.\r\n", got "The tao that can be told\nis not the eternal Tao\nThe name that can be named\nis not the eternal Name.\n\nThe unnamable is the eternally real.\nNaming is the origin\nof all particular things.\n\nFree from desire, you realize the mystery.\nCaught in desire, you see only the manifestations.\n\nYet mystery and manifestations\narise from the same source.\nThis source is called darkness.\n\nDarkness within darkness.\nThe gateway to all understanding.\n"
--- FAIL: TestListFilesGlob (0.00s)
    sources_test.go:226: Want "testdata/multiple_files/1.txt\ntestdata/multiple_files/2.txt\n", got "testdata\\multiple_files\\1.txt\ntestdata\\multiple_files\\2.txt\n"
--- FAIL: TestListFilesMultipleFiles (0.00s)
    sources_test.go:193: Want "testdata/multiple_files/1.txt\ntestdata/multiple_files/2.txt\ntestdata/multiple_files/3.tar.zip\n", got "testdata\\multiple_files\\1.txt\ntestdata\\multiple_files\\2.txt\ntestdata\\multiple_files\\3.tar.zip\n"
--- FAIL: TestFindFiles (0.00s)
    --- FAIL: TestFindFiles/testdata/multiple_files (0.00s)
        sources_test.go:166: want "testdata/multiple_files/1.txt\ntestdata/multiple_files/2.txt\ntestdata/multiple_files/3.tar.zip\n", got "testdata\\multiple_files\\1.txt\ntestdata\\multiple_files\\2.txt\ntestdata\\multiple_files\\3.tar.zip\n"
    --- FAIL: TestFindFiles/testdata/multiple_files_with_subdirectory (0.00s)
        sources_test.go:166: want "testdata/multiple_files_with_subdirectory/1.txt\ntestdata/multiple_files_with_subdirectory/2.txt\ntestdata/multiple_files_with_subdirectory/3.tar.zip\ntestdata/multiple_files_with_subdirectory/dir/.hidden\ntestdata/multiple_files_with_subdirectory/dir/1.txt\ntestdata/multiple_files_with_subdirectory/dir/2.txt\n", got "testdata\\multiple_files_with_subdirectory\\1.txt\ntestdata\\multiple_files_with_subdirectory\\2.txt\ntestdata\\multiple_files_with_subdirectory\\3.tar.zip\ntestdata\\multiple_files_with_subdirectory\\dir\\.hidden\ntestdata\\multiple_files_with_subdirectory\\dir\\1.txt\ntestdata\\multiple_files_with_subdirectory\\dir\\2.txt\n"
--- FAIL: TestSHA256Sum (0.00s)
    sinks_test.go:163: want "a562c9c95e2ff3403e7ffcd8508c6b54d47d5f251387758d3e63dbaaa8296341", got "4aea3d470d3f667fdd2dcdb9dbbc77db43872cfbfac1ce15682c4928eae9a146"
--- FAIL: TestSHA256Sums (0.00s)
    filters_test.go:573: "testdata/sha256Sum.input.txt": want "1870478d23b0b4db37735d917f4f0ff9393dd3e52d8b0efa852ab85536ddad8e\n", got "ee3344681d9520a4cdde448bfc2c895fd77362355927ab5f80675eff4541624b\n"
--- FAIL: TestFreq (0.00s)
    filters_test.go:305: want "10 apple\r\n 4 banana\r\n 4 orange\r\n 1 kumquat\r\n", got "10 apple\n 4 banana\n 4 orange\n 1 kumquat\n"
--- FAIL: TestFirst (0.00s)
    filters_test.go:251: want "The tao that can be told\r\nis not the eternal Tao\r\nThe name that can be named\r\nis not the eternal Name.\r\n\r\nThe unnamable is the eternally real.\r\nNaming is the origin\r\nof all particular things.\r\n\r\nFree from desire, you realize the mystery.\r\n", got "The tao that can be told\nis not the eternal Tao\nThe name that can be named\nis not the eternal Name.\n\nThe unnamable is the eternally real.\nNaming is the origin\nof all particular things.\n\nFree from desire, you realize the mystery.\n"
    filters_test.go:290: want "The tao that can be told\r\nis not the eternal Tao\r\nThe name that can be named\r\nis not the eternal Name.\r\n\r\nThe unnamable is the eternally real.\r\nNaming is the origin\r\nof all particular things.\r\n\r\nFree from desire, you realize the mystery.\r\nCaught in desire, you see only the manifestations.\r\n\r\nYet mystery and manifestations\r\narise from the same source.\r\nThis source is called darkness.\r\n\r\nDarkness within darkness.\r\nThe gateway to all understanding.\r\n", got "The tao that can be told\nis not the eternal Tao\nThe name that can be named\nis not the eternal Name.\n\nThe unnamable is the eternally real.\nNaming is the origin\nof all particular things.\n\nFree from desire, you realize the mystery.\nCaught in desire, you see only the manifestations.\n\nYet mystery and manifestations\narise from the same source.\nThis source is called darkness.\n\nDarkness within darkness.\nThe gateway to all understanding.\n"
--- FAIL: TestDirname (0.00s)
    filters_test.go:128: "/": want "/\n", got "\\\n"
    filters_test.go:128: "/root": want "/\n", got "\\\n"
    filters_test.go:128: "/tmp/example.php": want "/tmp\n", got "\\tmp\n"
    filters_test.go:128: "/var/tmp/example.php": want "/var/tmp\n", got "\\var\\tmp\n"
    filters_test.go:128: "/var/tmp": want "/var\n", got "\\var\n"
    filters_test.go:128: "/var/tmp/": want "/var\n", got "\\var\n"
    filters_test.go:128: "/tmp/script-21345.txt\n/tmp/script-5371253.txt": want "/tmp\n/tmp\n", got "\\tmp\n\\tmp\n"
    filters_test.go:128: "C:/Program Files/PHP": want "C:/Program Files\n", got "C:\\Program Files\n"
    filters_test.go:128: "C:/Program Files/PHP/": want "C:/Program Files\n", got "C:\\Program Files\n"
    filters_test.go:128: "C:/Program Files": want "C:\n", got "C:\\\n"
--- FAIL: TestColumn (0.00s)
    filters_test.go:52: want "Ss+\r\nR+\r\nSs\r\nSs+\r\nSs+\r\nSs+\r\nSs+\r\nSs\r\n", got "Ss+\nR+\nSs\nSs+\nSs+\nSs+\nSs+\nSs\n"
--- FAIL: ExampleFindFiles (0.00s)
got:
testdata\multiple_files_with_subdirectory\1.txt
testdata\multiple_files_with_subdirectory\2.txt
testdata\multiple_files_with_subdirectory\3.tar.zip
testdata\multiple_files_with_subdirectory\dir\.hidden
testdata\multiple_files_with_subdirectory\dir\1.txt
testdata\multiple_files_with_subdirectory\dir\2.txt
want:
testdata/multiple_files_with_subdirectory/1.txt
testdata/multiple_files_with_subdirectory/2.txt
testdata/multiple_files_with_subdirectory/3.tar.zip
testdata/multiple_files_with_subdirectory/dir/.hidden
testdata/multiple_files_with_subdirectory/dir/1.txt
testdata/multiple_files_with_subdirectory/dir/2.txt
--- FAIL: ExampleListFiles (0.00s)
got:
testdata\multiple_files_with_subdirectory\1.txt
testdata\multiple_files_with_subdirectory\2.txt
testdata\multiple_files_with_subdirectory\3.tar.zip
testdata\multiple_files_with_subdirectory\dir
want:
testdata/multiple_files_with_subdirectory/1.txt
testdata/multiple_files_with_subdirectory/2.txt
testdata/multiple_files_with_subdirectory/3.tar.zip
testdata/multiple_files_with_subdirectory/dir
--- FAIL: ExamplePipe_Basename (0.00s)
got:
.
\
root
example.php
tmp
filters
Program Files
want:
.
/
root
example.php
tmp
filters
Program Files
--- FAIL: ExamplePipe_Concat (0.00s)
got:
This is the first line in the file.
Hello, world.
This is another line in the file.
hello world
want:
This is the first line in the file.
Hello, world.
This is another line in the file.
hello world
--- FAIL: ExamplePipe_Dirname (0.00s)
got:
.
\
\
\tmp
\var
./src
C:\
want:
.
/
/
/tmp
/var
./src
C:
--- FAIL: ExamplePipe_SHA256Sums (0.00s)
got:
4aea3d470d3f667fdd2dcdb9dbbc77db43872cfbfac1ce15682c4928eae9a146
want:
a562c9c95e2ff3403e7ffcd8508c6b54d47d5f251387758d3e63dbaaa8296341
FAIL
exit status 1
FAIL	github.com/bitfield/script	1.526s
```

**Comment by bitfield** [comment]
Could you check out the `windows` branch and try the tests on that?

**Comment by bitfield** [comment]
Many thanks for the report, and all your help debugging the problems, @No-one-important. I've set up CI tests against a Windows image, and they're now passing, so I'm going to call this done! If you're still seeing failures, we can look at that in a separate issue.

**Pull request merged**
