### PR TITLE
Add ExecArgs source and filter

### PR DESCRIPTION
**Pull request by lalloni**
Would help to solve #61.

### CODE REVIEW

**Comment by lalloni** [comment]
Hey @bitfield, any chance of this being considered?

**Comment by bitfield** [comment]
Not at the moment, @lalloni: I mentioned in a comment on your issue that I haven't yet seen a problem that this solves. If you have one, of course I'll be pleased to see the program that demonstrates it.

**Comment by lalloni** [comment]
When building long command lines with more than a few computed arguments to pass to it, the requirement of using shell style quoted syntax makes the library harder to use and introduces a opportunities to do it wrong (like forgetting to quote arguments that could contain spaces).

For example, let's take the execution of the go tool to build a binary...

Basic shell execution would be like:

```sh
go build -ldflags '-X main.version=1.2.3' -o 'build/some-program' 'cmd/some-program/main.go'
```

If we build that line from a go program that executes the go tool to build all the binaries in a given project, it would naturally be something as simple as:

```go
out, err := foo.Exec("go", "build", "-ldflags", "-X main.version=1.2.3", "-o", "build/some-program", "cmd/some-program/main.go").String()
// do something with err/out, etc...
```

Note that the strings passed above do not need any further processing before passing them to the command execution function used to run the actual command (either `os.StartProcess()` or `os/exec.Command()`), and they are also in the right granularity so avoiding any quoting to demark arguments boundaries.

Of course since our build tool would need to potentially build many binaries we need to introduce some variables to loop over the `cmd/` subdirectories and to compute where to write each final binary, as well as for the version to use:

```go
out, err := foo.Exec("go", "build", "-ldflags", "-X main.version="+version, "-o", filepath.Join(buildDir, programName), filepath.Join(cmdDir, "main.go")).String()
// do something with err/out, etc...
```

Which is the minimum we need to write without introducing complexities related to shell syntax and quoting (as you can see there is no need at all to parse these strings looking for quoting, `foo.Exec` only needs to pass the `[]string` it receives to `os/exec.Command()` or even to `os.StartProcess()` without any kind of massage.

In contrast, using `bitfield/script.Exec()` requires the code to compute a single string with proper quoting and compatible syntax so it can at its turn parse it and split it back to pass it to the underlying command execution function, for example:

```go
out, err := script.Exec("go build -ldflags '-X main.version="+version+"' -o '"+ filepath.Join(BuildDir, binary) +"' '" + filepath.Join(".", binary, "main.go")).String()
// do something with err/out, etc...
```

Which is way harder to write, to not make any mistakes on the quoting, and it is also less efficient since we are "inventing" a string just to satisfy the `script.Exec()` function that will need to parse it using some (arbitrary) syntax to be able to split it again back to get the `[]string` that we already started with in the first place!

So what my patch above does is simply adding an `Exec` function variant that can receive the strings that compose the command as a natural `[]string` and it simply passes it verbatim to the underlying command execution function. This saves the coder needing to build a quoted string which is awkward and error-prone and it also saves the library from parsing it just to split it back to the original slice form.

**Comment by lalloni** [comment]
So, @bitfield, the problem it solves is about needing to build a synthetic string using some shell-like syntax to demark the target command arguments when we originally have the simple `[]string` that we need to pass to the underlying execution function.

**Comment by bitfield** [comment]
How about something like this:

```go
objName := filepath.Join(BuildDir, binary)
sourcePath := filepath.Join(".", binary, "main.go")
buildCmd := fmt.Sprintf("go build -ldflags '-X main.version=%s' -o %q %q", version, objName, sourcePath)
out, err := script.Exec(buildCmd).String()
```

Does that solve your problem?

**Comment by lalloni** [comment]
Sure @bitfield, that is an alternative, as well as other possible additions we could make in the form of other helper functions to reduce the "boilerplate" code needed to build the longer command string using shell-like syntax... but that is besides the point.

The point is that the simplest possible thing is to simply receive the `[]string` and pass it as is to the underlying command execution function... we are adding unneeded complexity (on both client code and internal code) by demanding the use of the shell-like syntax... it's like we are in love with the idea of parsing/supporting such pattern as the only way of executing commands, and unfortunately is not the simplest one, and it not only adds complexity and inefficiency but also error-making opportunities.

**Comment by bitfield** [comment]
Sorry, but I'm not convinced by this. The `script` method that runs a command takes a single string, and if it's easier for you to build it up as a `[]string` for some reason, you can always use `strings.Join` to concatenate it. Even better, as I suggested, is to use `fmt.Sprintf` to interpolate data into the required string. (`script` also has `ExecForEach` for running the same command on lots of computed values.)

> we are adding unneeded complexity

We are refraining from adding unneeded complexity. We don't need two different ways to run commands; that is confusing for beginners, and superfluous for experienced programmers. Thanks for the suggestion, but there's a high bar to increasing the size of the `script` API, and while this is a good idea, it doesn't quite show enough benefit for the cost.

**Comment by kudenz** [comment]
Thank to tips

Pada tanggal Rab, 21 Apr 2021 19.58, Pablo Lalloni ***@***.***>
menulis:

**Comment by lalloni** [comment]
> Sorry, but I'm not convinced by this. The `script` method that runs a command takes a single string, and if it's easier for you to build it up as a `[]string` for some reason, you can always use `strings.Join` to concatenate it. Even better, as I suggested, is to use `fmt.Sprintf` to interpolate data into the required string. (`script` also has `ExecForEach` for running the same command on lots of computed values.)

`strings.Join` helps little because we need to quote, `fmt.Sprintf` isn't enough when we don't know the number of elements (not to mention we need to write "code" with a "format" strings like `"%q %q %q %q"` which is just plain... a bother and error prone)... in both cases we would scramble to add a helper functions to save all of that.

> We are refraining from adding unneeded complexity. We don't need two different ways to run commands; that is confusing for beginners, and superfluous for experienced programmers. Thanks for the suggestion, but there's a high bar to increasing the size of the `script` API, and while this is a good idea, it doesn't quite show enough benefit for the cost.

Unfortunately, the way that was chosen to run commands is not the simplest possible one because instead of focusing in running commands it also attempts to parse some command arbitrary syntax and that is what creates this discussion. That's the added complexity. 

The simplest possible function to run commands would just receive a `[]string` and would not try to invent/parse a syntax or require client code to deal with it.

Quoting/Unquoting, parsing, etc. is a shell's business... not a command execution function's, and much less it is something I would like to deal with as a client code writer.

If I wanted to execute something as simple as `cut -d "` using this smarty pants unquoting execution function I'd be forced  to write something like:

```go
script.Exec(fmt.Sprintf("cut -d %q", "\""))
```

Which is totally unnecessary, when we could simply say:

```go
script.Exec("cut", "-d", "\"")
```

Just as we would when using the standard library with:

```go
exec.Command("cut", "-d", "\"")
```

**Comment by bitfield** [comment]
I think this will do what you want:

```go
script.Exec("cut -d \"")
```

**Pull request closed without merging**
