### PR TITLE
Add ListFiles() source

### PR DESCRIPTION
**Pull request by abtin**
Added ListFiles(), updated sources_test.go and README.md and also provided an example.

### CODE REVIEW

**Comment by bitfield** [comment]
@abtin thank you! Have you seen #2? Maybe you guys should get together :)

**Comment by bitfield** [comment]
@abtin are you interested in contributing to the other PR (#2)? If not, do you mind if I combine the best of both PRs?

**Comment by abtin** [comment]
Sure @bitfield. I'll take a look at (#2
<https://github.com/bitfield/script/pull/2>) once I get back to my desk to
see how I can contribute to it. Any suggestions?

**Comment by bitfield** [comment]
> Any suggestions?

I'm not sure yet. I've done a detailed code review on the other one and asked for changes; I'm following up with the author to see if he wants to continue working on it. If not, I propose to pick up the PR, finish up the changes, incorporate anything from this PR which is additional or better, and perhaps we can work together on finishing it off.

**Comment by abtin** [comment]
@bitfield Sounds like a plan to me. I read the other PR and your suggestions. I can apply them or if (#2) prefers to use any parts of my PR, I'm fine with that too.

**Comment by SmilingNavern** [comment]
I've updated #2 . Feel free to add whatever i've missed there. I've used Readme from this pull request and `ContainsAny` line.

**Comment by bitfield** [comment]
If you don't mind, @abtin, I'll close this one, as we've combined the best of both PRs into #2 — and I'd appreciate your comments and suggestions for that one.

**Comment by abtin** [comment]
Absolutely. Please go ahead.

**Pull request closed without merging**
